In [1]:
# Importing Libaries
import pandas as pd

In [2]:
# Loading dataset
df = pd.read_csv(r"D:\Data Analyst Stuff\WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [3]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [4]:
# Quick overview, checking for missing entries, data types etc
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB
None

In [5]:
# Checking for missing values
print(df.isnull().sum())

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [6]:
# Checking for duplicate rows
print(df.duplicated().sum())

0

In [7]:
print(df.dtypes)

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [8]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"])

ValueError: Unable to parse string " " at position 488

In [9]:
# Earlier we had no null entries however upon trying to convert TotalCharges from object to float64 we encountered the error above so inspecting " " entries.
df[df["TotalCharges"] == " "]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,No

In [10]:
# Proceeding with conversion. 
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

In [11]:
print(df.isnull().sum())

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [12]:
# Inspecting the now null entries now that they aren't just " " to decide whether to fill or drop.
df[df["TotalCharges"].isnull()]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No

In [13]:
# Dropping the 11 null entries. 
df = df.dropna(subset=["TotalCharges"])

In [43]:
# Rechecking null entries to make sure there is now none again. 
print(df.isnull().sum())

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
Churn_Flag          0
Both_Streaming      0
dtype: int64

In [14]:
# Checking data types to see if TotalCharges has converted from object to float64
print(df.dtypes)

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn                object
dtype: object

In [15]:
# EDA Section

In [ ]:
# What's the overall churn rate?

In [21]:
df.loc[:, "Churn_Flag"] = df["Churn"].map({"Yes": 1, "No": 0})

In [22]:
print(df[["Churn", "Churn_Flag"]].head())

  Churn  Churn_Flag
0    No           0
1    No           0
2   Yes           1
3    No           0
4   Yes           1

In [23]:
churn_rate = df["Churn_Flag"].mean()
print(f"Overall Churn Rate: {churn_rate:.2%}")

Overall Churn Rate: 26.58%

In [ ]:
# Which contract type has the highest churn?

In [24]:
contract_churn = (df.groupby("Contract")["Churn_Flag"].mean().sort_values(ascending=False) * 100)

print(contract_churn)

Contract
Month-to-month    42.709677
One year          11.277174
Two year           2.848665
Name: Churn_Flag, dtype: float64

In [ ]:
# Does tenure affect churn?

In [25]:
print(df.groupby("Churn")["tenure"].describe())

        count       mean        std  min   25%   50%   75%   max
Churn
No     5163.0  37.650010  24.076940  1.0  15.0  38.0  61.0  72.0
Yes    1869.0  17.979133  19.531123  1.0   2.0  10.0  29.0  72.0

In [26]:
tenure_avg = df.groupby("Churn")["tenure"].mean()
print(tenure_avg)

Churn
No     37.650010
Yes    17.979133
Name: tenure, dtype: float64

In [ ]:
# Do customers with higher monthly charges churn more?

In [27]:
monthly_avg = df.groupby("Churn")["MonthlyCharges"].mean()
print(monthly_avg)

Churn
No     61.307408
Yes    74.441332
Name: MonthlyCharges, dtype: float64

In [ ]:
# Does Tech Support reduce churn?

In [28]:
tech_churn = (df.groupby("TechSupport")["Churn_Flag"].mean() * 100)
print(tech_churn)

TechSupport
No                     41.647465
No internet service     7.434211
Yes                    15.196078
Name: Churn_Flag, dtype: float64

In [ ]:
# Does InternetService affect churn?

In [29]:
internet_churn = (df.groupby("InternetService")["Churn_Flag"].mean() * 100)
print(internet_churn)

InternetService
DSL            18.998344
Fiber optic    41.892765
No              7.434211
Name: Churn_Flag, dtype: float64

In [31]:
fiber_price_check = df.groupby("InternetService").agg(
    Avg_Monthly_Charges=("MonthlyCharges", "mean"),
    Churn_Rate=("Churn_Flag", lambda x: x.mean() * 100),
    Customer_Count=("Churn_Flag", "count"),
)

print(fiber_price_check.round(2))

                 Avg_Monthly_Charges  Churn_Rate  Customer_Count
InternetService
DSL                            58.09       19.00            2416
Fiber optic                    91.50       41.89            3096
No                             21.08        7.43            1520

In [ ]:
# Senior vs Non-Senior Churn Rate

In [34]:
senior_churn = df.groupby("SeniorCitizen").agg(
    Customer_Count=("Churn_Flag", "count"),
    Avg_Monthly_Charges=("MonthlyCharges", "mean"),
    Churn_Rate=("Churn_Flag", lambda x: x.mean() * 100),
)

print(senior_churn.round(2))

               Customer_Count  Avg_Monthly_Charges  Churn_Rate
SeniorCitizen
0                        5890                61.89       23.65
1                        1142                79.82       41.68

In [ ]:
# Does Phone Service affect Churn Rate?

In [47]:
phone_counts = df["PhoneService"].value_counts()
phone_pcts = df["PhoneService"].value_counts(normalize=True) * 100

phone_summary = pd.DataFrame({"Count": phone_counts, "Percentage (%)": phone_pcts.round(2)})

print(phone_summary)

              Count  Percentage (%)
PhoneService
Yes            6352           90.33
No              680            9.67

In [36]:
lines_summary = df["MultipleLines"].value_counts(normalize=True) * 100
print(lines_summary.round(2).astype(str) + "%")

MultipleLines
No                  48.14%
Yes                 42.19%
No phone service     9.67%
Name: proportion, dtype: object

In [45]:
phone_by_age = pd.crosstab(df["SeniorCitizen"], df["PhoneService"], normalize="index") * 100

phone_by_age.index = ["Non-Senior", "Senior"]
print("--- Phone Service Adoption by Age Group (%) ---")
print(phone_by_age.round(2))

--- Phone Service Adoption by Age Group (%) ---
PhoneService    No    Yes
Non-Senior    9.78  90.22
Senior        9.11  90.89

In [ ]:
# Which contracts opt in for streaming add-ons?

In [48]:
# Streaming TV adoption % by Contract Type
tv_by_contract = (pd.crosstab(df["Contract"], df["StreamingTV"], normalize="index")["Yes"]* 100)

# Streaming Movies adoption % by Contract Type
movies_by_contract = (pd.crosstab(df["Contract"], df["StreamingMovies"], normalize="index")["Yes"]* 100)

# Combining results into one table
streaming_contract_summary = pd.DataFrame({"Streaming TV Opt-In %": tv_by_contract, "Streaming Movies Opt-In %": movies_by_contract})

print(streaming_contract_summary.round(2))

                Streaming TV Opt-In %  Streaming Movies Opt-In %
Contract
Month-to-month                  33.50                      33.65
One year                        44.29                      44.97
Two year                        44.69                      45.40

In [49]:
# Create a helper flag for customers who have BOTH streaming add-ons
df.loc[:, "Both_Streaming"] = (df["StreamingTV"] == "Yes") & (df["StreamingMovies"] == "Yes")

# Aggregate adoption rate of both services by Contract
full_package = df.groupby("Contract")["Both_Streaming"].mean() * 100

print("--- % of Customers with BOTH Streaming TV & Movies ---")
print(full_package.round(2).astype(str) + "%")

--- % of Customers with BOTH Streaming TV & Movies ---
Contract
Month-to-month    20.98%
One year          33.29%
Two year          37.74%
Name: Both_Streaming, dtype: object

In [44]:
# Exporting cleaned CSV to load into Power BI to visualize the EDA. 
df.to_csv("telco_churn_cleaned.csv", index=False)